#!/bin/bash
if [ "$1" == "install" ]; then
    echo 'copying' $0 'to ./.git/hooks/pre-commit'
    cp $0 ./.git/hooks/pre-commit
    exit 0
fi
set -e

# test installation in a virtual environment
virtualenv -p $(which python) testenv
source testenv/bin/activate
make install

# run tests
make test

# generate docs
make docs

# cleanup
rm -rf testenv
