#!/bin/bash
if [ "$1" == "install" ]; then
    echo 'copying' $0 'to ./.git/hooks/pre-commit'
    cp $0 ./.git/hooks/pre-commit
    exit 0
fi
set -e
# run tests
make test

# test installation in a virtual environment
virtualenv -p $(which python3.6) testenv
source testenv/bin/activate
make install
rm -rf testenv

# generate docs
make docs
